# Generated by Django 3.0.2 on 2020-10-17 17:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dininghall',
            name='description',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='type',
            field=models.TextField(default='bruh'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_id', models.UUIDField(default=uuid.uuid4)),
                ('type', models.TextField()),
                ('food', models.ManyToManyField(to='dining.Food')),
            ],
        ),
        migrations.AddField(
            model_name='dininghall',
            name='breakfast',
            field=models.ManyToManyField(related_name='breakfast', to='dining.Meal'),
        ),
        migrations.AddField(
            model_name='dininghall',
            name='dinner',
            field=models.ManyToManyField(related_name='dinner', to='dining.Meal'),
        ),
        migrations.AddField(
            model_name='dininghall',
            name='lunch',
            field=models.ManyToManyField(related_name='lunch', to='dining.Meal'),
        ),
    ]
