# Generated by Django 3.1.2 on 2020-10-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0002_auto_20201017_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='end_time',
            field=models.CharField(default='bc', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='start_time',
            field=models.CharField(default='bc', max_length=8),
            preserve_default=False,
        ),
    ]
